# Generated by Django 5.2.15 on 2026-06-11 12:24

import config.storage_backends
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_testimonial_review_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('issuer', models.CharField(max_length=255)),
                ('issue_date', models.CharField(help_text='e.g. Nov 2025', max_length=100)),
                ('description', models.TextField()),
                ('thumbnail_image', models.ImageField(blank=True, help_text='Optional preview image', null=True, storage=config.storage_backends.CertificatesStorage(), upload_to='')),
                ('certificate_pdf', models.FileField(help_text='Upload certificate PDF', storage=config.storage_backends.CertificatesStorage(), upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
            ],
        ),
        migrations.CreateModel(
            name='CVAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_pdf', models.FileField(blank=True, help_text='Upload your latest CV/Resume (PDF).', null=True, storage=config.storage_backends.CVFilesStorage(), upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
            ],
            options={
                'verbose_name': 'CV Asset',
                'verbose_name_plural': 'CV Assets',
            },
        ),
        migrations.CreateModel(
            name='ProfileAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, help_text='Upload your main profile photo.', null=True, storage=config.storage_backends.ProfileAssetsStorage(), upload_to='')),
                ('hero_image', models.ImageField(blank=True, help_text='Upload your hero/banner image.', null=True, storage=config.storage_backends.ProfileAssetsStorage(), upload_to='')),
            ],
            options={
                'verbose_name': 'Profile & Hero Asset',
                'verbose_name_plural': 'Profile & Hero Assets',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Bigendra Shrestha', max_length=255)),
                ('title', models.CharField(default='Python & AI Trainee | Data Science Intern Aspirant', max_length=255)),
                ('bio', models.TextField(default='I am an enthusiastic beginner in Python and AI with recent certifications in Python 3.X and Generative AI. I enjoy building data science workflows, preprocessing pipelines, and backend applications using clean code practices.\n\nI am seeking a trainee or internship position where I can apply programming, data analysis, and model-building skills while continuing to learn and contribute with dedication.')),
                ('location', models.CharField(default='Kathmandu, Nepal', max_length=255)),
                ('phone', models.CharField(default='+977 9860297032', max_length=50)),
                ('whatsapp', models.CharField(default='+977 9860297032', max_length=50)),
                ('viber', models.CharField(default='+977 9860297032', max_length=50)),
                ('email', models.EmailField(default='Bige.stha@gmail.com', max_length=254)),
                ('github', models.URLField(default='https://github.com/potat0ka')),
                ('linkedin', models.URLField(default='https://www.linkedin.com/in/bigendrashrestha/')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.DeleteModel(
            name='PortfolioAsset',
        ),
    ]
