# Generated by Django 5.2.15 on 2026-06-12 12:52

import apps.core.storage
import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='certificate_pdf',
            field=models.FileField(help_text='Upload certificate PDF.', storage=apps.core.storage.certificates_storage, upload_to='', validators=[django.core.validators.FileExtensionValidator(('pdf',)), apps.core.validators.validate_pdf_upload_size]),
        ),
        migrations.AlterField(
            model_name='certification',
            name='thumbnail_image',
            field=models.ImageField(blank=True, help_text='Optional preview image (jpg, jpeg, png, webp).', null=True, storage=apps.core.storage.certificates_storage, upload_to='', validators=[django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png', 'webp')), apps.core.validators.validate_image_upload_size]),
        ),
        migrations.AlterField(
            model_name='cvasset',
            name='cv_pdf',
            field=models.FileField(blank=True, help_text='Upload your latest CV/Resume (PDF only).', null=True, storage=apps.core.storage.cv_files_storage, upload_to='', validators=[django.core.validators.FileExtensionValidator(('pdf',)), apps.core.validators.validate_pdf_upload_size]),
        ),
        migrations.AlterField(
            model_name='profileasset',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Upload your hero/banner image (jpg, jpeg, png, webp).', null=True, storage=apps.core.storage.profile_assets_storage, upload_to='', validators=[django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png', 'webp')), apps.core.validators.validate_image_upload_size]),
        ),
        migrations.AlterField(
            model_name='profileasset',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Upload your main profile photo (jpg, jpeg, png, webp).', null=True, storage=apps.core.storage.profile_assets_storage, upload_to='', validators=[django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png', 'webp')), apps.core.validators.validate_image_upload_size]),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(choices=[('Familiar / Beginner', 'Familiar / Beginner'), ('Proficient / Competent', 'Proficient / Competent'), ('Expert / Advanced', 'Expert / Advanced')], default='Familiar / Beginner', help_text='Proficiency level', max_length=50),
        ),
    ]
