# Generated by Django 5.2.15 on 2026-06-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_certification_certificate_pdf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('hero_played', models.CharField(help_text='Tech stack or hero used for the watch entry', max_length=255)),
                ('duration', models.CharField(max_length=100)),
                ('outcome', models.CharField(choices=[('VICTORY', 'Victory'), ('DEFEAT', 'Defeat')], default='VICTORY', max_length=16)),
                ('gpm', models.PositiveIntegerField(default=0)),
                ('role', models.CharField(max_length=100)),
                ('tech_keywords', models.JSONField(blank=True, default=list)),
                ('description', models.TextField()),
                ('impact_metrics', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project Watch',
                'verbose_name_plural': 'Project Watches',
                'ordering': ['-updated_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='WorkPatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, unique=True)),
                ('date', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('changes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patch Note',
                'verbose_name_plural': 'Patch Notes',
                'ordering': ['-created_at', 'version'],
            },
        ),
    ]
