# Generated by Django 5.2.15 on 2026-06-15 02:56

from django.db import migrations


WORK_PATCHES = [
    {
        "version": "v3.15.0",
        "date": "June 2026",
        "title": "STRENGTHENING BACKEND THROUGHPUT & SECURE INFRASTUCTURES",
        "category": "Dynamic Project Developer Core",
        "changes": [
            "Django REST Framework: Mana cost of nested serializers reduced. Optimized select_related and prefetch_related filters, dropping search database query latencies by 42%.",
            "Data Pipelines: Substituted standard iteration loops with Pandas vectorized mapping matrices, boosting aggregate ingestion speeds by 18%.",
            "Relational Tuning: Established precise secondary indexes in key tables, neutralizing system cooldown lag during periods of heavy writes.",
            "Security Buff Activation: Enforced strict csrf cryptographic cookie tokens, hardened headers, and locked frame embedded clickjack routes."
        ]
    },
    {
        "version": "v3.12.2",
        "date": "November 2025",
        "title": "ALGORITHMIC TARGETING MODELS & SERVER CLUSTERING",
        "category": "Academic & Data Science Explorer",
        "changes": [
            "Predictive Targeting Strategy: Integrated automated Scikit-Learn classifier arrays in server side, predicting recruiter matchmaking requests with 94.6% accuracy.",
            "Memory Stability Patch: Isolated a system leakage in massive matrix logs. Re-arranged operations to reuse pre-allocated NumPy storage buffers.",
            "API Autodocs Upgrade: Set up automated OpenAPI definitions generator, aligning frontend devs binding speeds on the main interface."
        ]
    },
    {
        "version": "v3.08.0",
        "date": "February 2024",
        "title": "LEGACY PIPELINE SCALE & INFRASTRUCTURE AUTOMATION",
        "category": "IT Tech Enthusiast Core",
        "changes": [
            "Automated Migration Engine: Drafted 150+ robust Django database migration schemas, seamlessly moving legacy shards with zero active gameplay disconnects.",
            "Analytics Dashboard Buff: Programmed customizable visual metric filters, allowing recruiters real-time insights into system health benchmarks.",
            "Error Isolation Systems: Configured automated logs notifying channel units immediately upon server request failures."
        ]
    }
]

PROJECT_MATCHES = [
    {
        "match_id": "PROJECT #001",
        "title": "Personal Technical Blog",
        "hero_played": "Python + Static Web",
        "duration": "Ongoing",
        "outcome": "VICTORY",
        "gpm": 360,
        "role": "Author / Developer",
        "tech_keywords": ["Python", "HTML", "CSS", "GitHub Pages"],
        "description": "Designed and published a personal technical blog to share Python experimentation, data science learning notes, and small automation projects.",
        "impact_metrics": [
            "Published developer content on GitHub Pages",
            "Maintains a growing technical portfolio of Python and data science articles",
            "Demonstrates consistent project documentation and learning progress"
        ]
    },
    {
        "match_id": "PROJECT #002",
        "title": "Phishing Detection Platform",
        "hero_played": "Python + Machine Learning",
        "duration": "3 Months",
        "outcome": "VICTORY",
        "gpm": 720,
        "role": "Data Science Developer",
        "tech_keywords": ["Python", "Pandas", "NumPy", "Machine Learning"],
        "description": "Built a phishing detection platform with Python, using data preprocessing and feature analysis to identify suspicious URL patterns.",
        "impact_metrics": [
            "Implemented dataset processing for phishing classification",
            "Published the codebase publicly on GitHub",
            "Validated model predictions on sample phishing cases"
        ]
    },
    {
        "match_id": "PROJECT #003",
        "title": "House Price Prediction System",
        "hero_played": "Data Science + Python",
        "duration": "1 Month",
        "outcome": "VICTORY",
        "gpm": 650,
        "role": "Data Science Intern",
        "tech_keywords": ["Python", "Pandas", "Scikit-Learn", "Matplotlib"],
        "description": "Developed a house price prediction system using data science workflows and regression modeling shared during an online webinar.",
        "impact_metrics": [
            "Designed a data science pipeline for housing prices",
            "Visualized model outputs with Matplotlib plots",
            "Delivered webinar-ready demo content for learners"
        ]
    }
]

def seed_data(apps, schema_editor):
    WorkPatch = apps.get_model('core', 'WorkPatch')
    ProjectMatch = apps.get_model('core', 'ProjectMatch')

    for patch in WORK_PATCHES:
        WorkPatch.objects.get_or_create(
            version=patch["version"],
            defaults={
                "date": patch["date"],
                "title": patch["title"],
                "category": patch["category"],
                "changes": patch["changes"]
            }
        )
        
    for match in PROJECT_MATCHES:
        ProjectMatch.objects.get_or_create(
            match_id=match["match_id"],
            defaults={
                "title": match["title"],
                "hero_played": match["hero_played"],
                "duration": match["duration"],
                "outcome": match["outcome"],
                "gpm": match["gpm"],
                "role": match["role"],
                "tech_keywords": match["tech_keywords"],
                "description": match["description"],
                "impact_metrics": match["impact_metrics"]
            }
        )

def reverse_seed_data(apps, schema_editor):
    WorkPatch = apps.get_model('core', 'WorkPatch')
    ProjectMatch = apps.get_model('core', 'ProjectMatch')
    WorkPatch.objects.all().delete()
    ProjectMatch.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_projectmatch_workpatch'),
    ]

    operations = [
        migrations.RunPython(seed_data, reverse_seed_data),
    ]
