# Generated by Django 5.2.15 on 2026-06-15 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_seed_portfolio_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='relationship',
            field=models.CharField(choices=[('manager', 'Current / Ex Bosses & Managers'), ('client', 'Clients & Customers'), ('college', 'College & University Friends'), ('coworker', 'Colleagues & Coworkers'), ('freelance', 'Freelance & Casual Projects')], default='coworker', max_length=20),
        ),
    ]
